res = {
    results: {
        id: "page-b5788f2810",
        designPath: "/libs/settings/wcm/designs/default",
        title: "PDP",
        brandSlug: "",
        lastModifiedDate: 1686570664439,
        templateName: "page-content",
        htmlPageItems: [],
        cssClassNames: "page basicpage",
        language: "en",
        ":itemsOrder": ["root"],
        ":items": {
            root: {
                columnCount: 12,
                gridClassNames: "aem-Grid aem-Grid--12 aem-Grid--default--12",
                columnClassNames: {
                    container: "aem-GridColumn aem-GridColumn--default--12",
                },
                ":itemsOrder": ["container"],
                ":items": {
                    container: {
                        columnCount: 12,
                        gridClassNames:
                            "aem-Grid aem-Grid--12 aem-Grid--default--12",
                        columnClassNames: {
                            recommendation_1160289521:
                                "aem-GridColumn aem-GridColumn--default--12",
                            recommendation_1858125872:
                                "aem-GridColumn aem-GridColumn--default--12",
                            recommendation:
                                "aem-GridColumn aem-GridColumn--default--12",
                            recommendation_1070648385:
                                "aem-GridColumn aem-GridColumn--default--12",
                        },
                        ":itemsOrder": [
                            "recommendation",
                            "recommendation_1858125872",
                            "recommendation_1160289521",
                            "recommendation_1070648385",
                        ],
                        ":items": {
                            recommendation: {
                                showSection: "show",
                                componentSelection: "recommend-you",
                                alignment: "left",
                                source: "image",
                                image: "",
                                altText: "",
                                video: "",
                                videoThumbnail: "",
                                imageVideoTitle: "",
                                imageVideoTitleColor: "",
                                imageVideoContentText: "",
                                imageVideoCtaLabel: "",
                                imageVideoTargetLink: "",
                                collectionId: "",
                                bgImage: "",
                                bgImageAltText: "",
                                bgColor: "",
                                title: "Complete The Look",
                                ctaLabel: "",
                                targetLink: "",
                                algonomyPlaceHolder: "item_page.recs_1",
                                enablePromoTimer: false,
                                startDate: "",
                                endDate: "",
                                items: [],
                                ":type":
                                    "mfl-superapp-aem/components/recommendation",
                            },
                            recommendation_1858125872: {
                                showSection: "show",
                                componentSelection: "recommend-you",
                                alignment: "left",
                                source: "image",
                                image: "",
                                altText: "",
                                video: "",
                                videoThumbnail: "",
                                imageVideoTitle: "",
                                imageVideoTitleColor: "",
                                imageVideoContentText: "",
                                imageVideoCtaLabel: "",
                                imageVideoTargetLink: "",
                                collectionId: "",
                                bgImage: "",
                                bgImageAltText: "",
                                bgColor: "",
                                title: "Curated For You",
                                ctaLabel: "",
                                targetLink: "",
                                algonomyPlaceHolder: "item_page.recs_2",
                                enablePromoTimer: false,
                                startDate: "",
                                endDate: "",
                                items: [],
                                ":type":
                                    "mfl-superapp-aem/components/recommendation",
                            },
                            recommendation_1160289521: {
                                showSection: "show",
                                componentSelection: "recommend-you",
                                alignment: "left",
                                source: "image",
                                image: "",
                                altText: "",
                                video: "",
                                videoThumbnail: "",
                                imageVideoTitle: "",
                                imageVideoTitleColor: "",
                                imageVideoContentText: "",
                                imageVideoCtaLabel: "",
                                imageVideoTargetLink: "",
                                collectionId: "",
                                bgImage: "",
                                bgImageAltText: "",
                                bgColor: "",
                                title: "View Similar",
                                ctaLabel: "",
                                targetLink: "",
                                algonomyPlaceHolder: "item_page.recs_3",
                                enablePromoTimer: false,
                                startDate: "",
                                endDate: "",
                                items: [],
                                ":type":
                                    "mfl-superapp-aem/components/recommendation",
                            },
                            recommendation_1070648385: {
                                showSection: "show",
                                componentSelection: "recommend-you",
                                alignment: "left",
                                source: "image",
                                image: "",
                                altText: "",
                                video: "",
                                videoThumbnail: "",
                                imageVideoTitle: "",
                                imageVideoTitleColor: "",
                                imageVideoContentText: "",
                                imageVideoCtaLabel: "",
                                imageVideoTargetLink: "",
                                collectionId: "",
                                bgImage: "",
                                bgImageAltText: "",
                                bgColor: "",
                                title: "Recently Viewed",
                                ctaLabel: "",
                                targetLink: "",
                                algonomyPlaceHolder: "item_page.recs_4",
                                enablePromoTimer: false,
                                startDate: "",
                                endDate: "",
                                items: [],
                                ":type":
                                    "mfl-superapp-aem/components/recommendation",
                            },
                        },
                        ":type": "mfl-superapp-aem/components/container",
                    },
                },
                ":type": "mfl-superapp-aem/components/container",
            },
        },
        ":type": "mfl-superapp-aem/components/page",
    },
};
