let resPayload = {
    success: true,
    results: [
        {
            storeCode: "99103",
            retekCode: "99103",
            storeName: "The Collective Chennai",
            subBrand: "",
            pinCode: 600042,
            emailId: "tc.chennai0059@abfrl.adityabirla.com",
            address:
                "Unit No: UG -11, Old door no:62 & New door no.142, Phonix market city, 42, Velachery Main Road, Velachery, Chennai, Tamil Nadu - 600042\n",
            cityName: "Ariyalur",
            cityId: 44,
            stateName: "Nurestan",
            stateId: 24,
            countryName: "Germany",
            phoneNumber: "044-66653806",
            whatsappNumber: "7550095471",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 12.9905,
            longitude: 80.217003,
        },
        {
            storeCode: "1234",
            retekCode: "4422",
            storeName: "TED Baker Mysore",
            subBrand: "Ted Baker",
            pinCode: 334004,
            emailId: "avi@gmail.com",
            address: "13/54 Mukta Prasad Nagar",
            cityName: "Alwar",
            cityId: 22,
            stateName: "Herat",
            stateId: 12,
            countryName: "Germany",
            phoneNumber: "9509780329",
            whatsappNumber: "",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 12.2958,
            longitude: 76.639397,
        },
        {
            storeCode: "99032",
            retekCode: "10000",
            storeName: "Hackett ",
            subBrand: "Hackett London",
            pinCode: 110070,
            emailId: "mlsha.deldlf@abfrl.adityabirla.com",
            address:
                "Hackett London,Shop No.206, Dlf Emporio, Vasant Kunj, New Delhi - 110 070.\n",
            cityName: "Karwar",
            cityId: 451,
            stateName: "Bulqiz",
            stateId: 36,
            countryName: "Germany",
            phoneNumber: "011-41087388",
            whatsappNumber: "8699597836",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 28.543877,
            longitude: 77.156876,
        },
        {
            storeCode: "99043",
            retekCode: "1000",
            storeName: "The Collective Bangalore ",
            subBrand: "",
            pinCode: 560001,
            emailId: "99043@collective.in",
            address:
                "The Collective, Unit No.101, 1st Floor Level, Concorde Block, UB City, No. 24, Vittal Mallya Road,Bangalore – 560 001\n",
            cityName: "Almora",
            cityId: 20,
            stateName: "Herat",
            stateId: 12,
            countryName: "Germany",
            phoneNumber: "080-41207331",
            whatsappNumber: "8970730765",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 0,
            longitude: 0,
        },
        {
            storeCode: "99035",
            retekCode: "100000035",
            storeName: "The Collective Kolkata",
            subBrand: "",
            pinCode: 700017,
            emailId: "99035@collective.in",
            address:
                "The Collective, Quest Mall, G.F. Shop #12,13,14, Syed Amir Ali Ave, Park Circus, Beck Bagan, Ballygunge,Kolkata, West Bengal - 700017\n",
            cityName: "Bagbassa",
            cityId: 58,
            stateName: "Panjshir",
            stateId: 28,
            countryName: "Germany",
            phoneNumber: "033-40620888",
            whatsappNumber: "9831827105",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 0,
            longitude: 0,
        },
        {
            storeCode: "99017",
            retekCode: "100000017",
            storeName: "The Collective Pune",
            subBrand: "",
            pinCode: 411028,
            emailId: "99017@collective.in",
            address:
                "The Collective, GF-02 & GF-03, Koregaon Park Plaza Mall, North, Main Road, Koregaon Park, Next to Westin Hotel,Pune - 411028 \n",
            cityName: "Anand",
            cityId: 34,
            stateName: "Kandahar",
            stateId: 15,
            countryName: "Germany",
            phoneNumber: "020-67040444",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 0,
            longitude: 0,
        },
        {
            storeCode: "99036",
            retekCode: "99036",
            storeName: "Hackett London Mumbai ",
            subBrand: "Hackett London",
            pinCode: 400013,
            emailId: "tathagata.sarkar@abfrl.adityabirla.com",
            address:
                "The Collective, Palladium Mall,Level 2 & 3, High Street Phoenix, Senapati Bapat Marg, Lower Parel, Mumbai-400013\n",
            cityName: "Amreli",
            cityId: 31,
            stateName: "Kandahar",
            stateId: 15,
            countryName: "Germany",
            phoneNumber: "022-43472888",
            whatsappNumber: "8080307030",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 18.993879,
            longitude: 72.824928,
        },
        {
            storeCode: "99110",
            retekCode: "9110",
            storeName: "Ted Baker",
            subBrand: "Ted Baker",
            pinCode: 110070,
            emailId: "tb.del0061@abfrl.adityabirla.com",
            address:
                "Ted Baker, Shop Number -209, Second Floor, The Chanakya Mall, Chanakyapuri, New Delhi-110021\n",
            cityName: "Karwar",
            cityId: 451,
            stateName: "Bulqiz",
            stateId: 36,
            countryName: "Germany",
            phoneNumber: "011-26886070",
            whatsappNumber: "9654340031",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 28.584299,
            longitude: 77.190697,
        },
        {
            storeCode: "99026",
            retekCode: "99026",
            storeName: "Hackett London Chandigarh",
            subBrand: "Hackett London",
            pinCode: 160002,
            emailId: "hackett.chandigarh@abfrl.adityabirla.com",
            address:
                "Hackett London, G 24 & 25, Ground Floor, Elante Mall, Industrial Area Phase 1, Chandigarh-160002\n",
            cityName: "Angul",
            cityId: 39,
            stateName: "Samangan",
            stateId: 30,
            countryName: "Germany",
            phoneNumber: "0172-4325888",
            whatsappNumber: "9779769688",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 30.705795,
            longitude: 76.800499,
        },
        {
            storeCode: "99043",
            retekCode: "99043",
            storeName: "The Collective Bangalore ",
            subBrand: "",
            pinCode: 560001,
            emailId: "naveen.gc@abfrl.adityabirla.com",
            address:
                "The Collective, Unit No.101, 1st Floor Level, Concorde Block, UB City, No. 24, Vittal Mallya Road,Bangalore – 560 001\n",
            cityName: "Almora",
            cityId: 20,
            stateName: "Herat",
            stateId: 12,
            countryName: "Germany",
            phoneNumber: "080-41207331",
            whatsappNumber: "8970730765",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 12.9716,
            longitude: 77.5961,
        },
        {
            storeCode: "99035",
            retekCode: "99035",
            storeName: "The Collective Kolkata",
            subBrand: "null",
            pinCode: 700017,
            emailId: "tc.kolkata@abfrl.adityabirla.com",
            address:
                "The Collective, Quest Mall, G.F. Shop #12,13,14, Syed Amir Ali Ave, Park Circus, Beck Bagan, Ballygunge,Kolkata, West Bengal - 700017",
            cityName: "Bagbassa",
            cityId: 58,
            stateName: "Panjshir",
            stateId: 28,
            countryName: "Germany",
            phoneNumber: "033-40620888",
            whatsappNumber: "9831827105",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 22.53904,
            longitude: 88.365685,
        },
        {
            storeCode: "99121",
            retekCode: "99121",
            storeName: "The Collective Pune",
            subBrand: "null",
            pinCode: 411016,
            emailId: "Pune.100000070@abfrl.adityabirla.com",
            address:
                "The Collective Express\nPavilion Mall, S B Road, Next to JW Marriott, Maharashtra -   411016\n",
            cityName: "Anand",
            cityId: 34,
            stateName: "Kandahar",
            stateId: 15,
            countryName: "Germany",
            phoneNumber: "7045007525",
            whatsappNumber: "7045007525",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 18.5338,
            longitude: 73.829803,
        },
        {
            storeCode: "99008",
            retekCode: "99008",
            storeName: "The Collective Mumbai",
            subBrand: "null",
            pinCode: 400013,
            emailId: "mls_tc_mumphx@abfrl.adityabirla.com",
            address:
                "The Collective, Palladium Mall,Level 2 & 3, High Street Phoenix, Senapati Bapat Marg, Lower Parel, Mumbai-400013,",
            cityName: "Amreli",
            cityId: 31,
            stateName: "Kandahar",
            stateId: 15,
            countryName: "Germany",
            phoneNumber: "022 4023 4414",
            whatsappNumber: "7835870906",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 18.993879,
            longitude: 72.824928,
        },
        {
            storeCode: "99023",
            retekCode: "99023",
            storeName: "The Collective Gurgaon ",
            subBrand: "",
            pinCode: 122002,
            emailId: "tc.gurgaon@abfrl.adityabirla.com",
            address:
                "The Collective, G,7& G 8, Ground Floor Ambience Mall, Ambience Island,  Nh 8, Gurgaon, Haryana. 122002",
            cityName: "Kashipur",
            cityId: 453,
            stateName: "Faryab",
            stateId: 8,
            countryName: "Germany",
            phoneNumber: "0124-4665888",
            whatsappNumber: "9051199457",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 28.504801,
            longitude: 77.097,
        },
        {
            storeCode: "99009",
            retekCode: "99009",
            storeName: "The Collective Vasant Kunj",
            subBrand: "null",
            pinCode: 110070,
            emailId: "99009@collective.in",
            address:
                "The Collective, No.28, Upper Ground & level 1, Ambience Mall, Vasant Kunj, New Delhi-110070, India,",
            cityName: "Agartala",
            cityId: 6,
            stateName: "Wardag",
            stateId: 33,
            countryName: "Germany",
            phoneNumber: "9988887877",
            whatsappNumber: "",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 28.5413,
            longitude: 77.154999,
        },
        {
            storeCode: "99024",
            retekCode: "99024",
            storeName: "The Collective Chandigarh",
            subBrand: "null",
            pinCode: 160002,
            emailId: "tc.chandigarh@abfrl.adityabirla.com",
            address:
                "The Collective, G 24 & 25, Elante Mall, Industrial & Business Park, Phase 1 - 160 002 , Chandigarh,",
            cityName: "Angul",
            cityId: 39,
            stateName: "Samangan",
            stateId: 30,
            countryName: "Germany",
            phoneNumber: "0172-4632888",
            whatsappNumber: "9996144030",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 30.705795,
            longitude: 76.800499,
        },
        {
            storeCode: "99020",
            retekCode: "99020",
            storeName: "Hackett London Bangalore ",
            subBrand: "Hackett London",
            pinCode: 560001,
            emailId: "mls_ha_blrubc@abfrl.adityabirla.com",
            address:
                "Hackett London, Shop No.14, Ground Floor,UB City, No. 24, Vittal Mallya Road Bangalore - 560 001\n",
            cityName: "Almora",
            cityId: 20,
            stateName: "Herat",
            stateId: 12,
            countryName: "Germany",
            phoneNumber: "080 4149 0999",
            whatsappNumber: "9123342513",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 12.972093,
            longitude: 77.595573,
        },
        {
            storeCode: "99035",
            retekCode: "100000035",
            storeName: "The Collective Kolkata",
            subBrand: "null",
            pinCode: 0,
            emailId: "700017",
            address: "",
            cityName: "Bagbassa",
            cityId: 58,
            stateName: "Panjshir",
            stateId: 28,
            countryName: "Germany",
            phoneNumber: "033-40620888",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 22.53904,
            longitude: 88.365685,
        },
        {
            storeCode: "99017",
            retekCode: "100000017",
            storeName: "The Collective Pune",
            subBrand: "null",
            pinCode: 0,
            emailId: "411028",
            address: "",
            cityName: "Anand",
            cityId: 34,
            stateName: "Kandahar",
            stateId: 15,
            countryName: "Germany",
            phoneNumber: "020-67040444",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 18.538181,
            longitude: 73.907585,
        },
        {
            storeCode: "99008",
            retekCode: "100000008",
            storeName: "The Collective Mumbai",
            subBrand: "null",
            pinCode: 0,
            emailId: "400013",
            address: "",
            cityName: "Amreli",
            cityId: 31,
            stateName: "Kandahar",
            stateId: 15,
            countryName: "Germany",
            phoneNumber: "022-40234414",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 18.993879,
            longitude: 72.824928,
        },
        {
            storeCode: "99023",
            retekCode: "100000023",
            storeName: "The Collective Gurgaon",
            subBrand: "null",
            pinCode: 0,
            emailId: "122002",
            address: "",
            cityName: "Kashipur",
            cityId: 453,
            stateName: "Faryab",
            stateId: 8,
            countryName: "Germany",
            phoneNumber: "0124-4665888",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 28.505325,
            longitude: 77.09642,
        },
        {
            storeCode: "99101",
            retekCode: "9101",
            storeName: "The Collective Denims",
            subBrand: "",
            pinCode: 110021,
            emailId: "tcdenim.del0058@abfrl.adityabirla.com",
            address:
                "The Collective Denims, Shop Number -208, Second Floor, The Chanakya Mall, Chanakyapuri, New Delhi - 110021\n",
            cityName: "Karwar",
            cityId: 451,
            stateName: "Bulqiz",
            stateId: 36,
            countryName: "Germany",
            phoneNumber: "011-26885060",
            whatsappNumber: "9999929611",
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 28.584299,
            longitude: 77.190697,
        },
        {
            storeCode: "99024",
            retekCode: "100000024",
            storeName: "The Collective Chandigarh",
            subBrand: "null",
            pinCode: 0,
            emailId: "160002",
            address: "",
            cityName: "Angul",
            cityId: 39,
            stateName: "Samangan",
            stateId: 30,
            countryName: "Germany",
            phoneNumber: "0172-4632888",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 30.705795,
            longitude: 76.800499,
        },
        {
            storeCode: "99043",
            retekCode: "100000043",
            storeName: "The Collective Bangalore",
            subBrand: "null",
            pinCode: 0,
            emailId: "560001",
            address: "",
            cityName: "Almora",
            cityId: 20,
            stateName: "Herat",
            stateId: 12,
            countryName: "Germany",
            phoneNumber: "080-41207331",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl: "",
            latitude: 12.972093,
            longitude: 77.595573,
        },
        {
            storeCode: "100064",
            retekCode: "31808",
            storeName: "VH Mainline JANPATH",
            subBrand: "",
            pinCode: 751009,
            emailId: "sr100064@abfrl.adityabirla.com",
            address:
                "ALLEN SOLLY,52/53 JANPATH,ASHOKNAGAR,BHUBANESWAR,ODISHA 751009",
            cityName: "Ananthapur",
            cityId: 36,
            stateName: "Laghman",
            stateId: 20,
            countryName: "Germany",
            phoneNumber: "0674-2533215",
            whatsappNumber: null,
            storeImage: "",
            offerImage: "",
            launchUrl:
                "https://www.allensolly.com/category/collections/collections-450?page=1&orderway=asc&orderby=popular&store__fq=31808",
            latitude: 20.264973,
            longitude: 85.839081,
        },
    ],
    msg: "",
    cache: 0,
    ttl: 0,
};
